name: Copy Files from Source Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run file copy action
        uses: DeWildeDaan/copy-from-repo@2.0.3
        with:
          source_repo: "DeWildeDaan/test-repo"
          source_path: "README.md"
          destination_path: "data/"
          commit_message: "Sync changes"
          pr_title: "Test PR"
          create_pr: "true"
          source_repo_token: ${{ secrets.SOURCE_REPO_PAT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}